movidius/ncappzoo

CONTRIBUTING.md, README.md
Branding, spelling, punctuation, and formatting
=> Edits made

apps/birds/Makefile, apps/birds/README.md, apps/birds/birds.py
Created the apps/birds project
=> added birds project

apps/birds/birds.py, apps/stream_ty_gn/Makefile, apps/stream_ty_gn/README.md, apps/stream_ty_gn/install-opencv-from_source.sh, apps/stream_ty_gn/stream_ty_gn.py
pull request for stream_ty_gn which runs tiny yolo inferences then googlenet for a camera stream
and small mod for birds
=> stream_ty_gn

apps/street_cam/Makefile, apps/street_cam/README.md, apps/street_cam/install-opencv-from_source.sh, apps/street_cam/street_cam.py
street_cam application initial version.
=> street_cam project

apps/topcoder_example/supporting/inferences.py
Signed-off-by: Julien Lerique <klo86min@free.fr>
=> change in log_loss: renormalization then clipping (reversed order).

apps/live-image-classifier/Makefile
There is nothing to clean but the top level make clean fails if every project doesn't have a 'make clean' so I added one that just echos to terminal .
=> added 'make clean' target to makefile.

apps/rapid-image-classifier/Makefile
Added a 'make clean' target to makefile.  it only echos to terminal since nothing to clean but the toplevel make clean was failing.
=> added make clean so top level make works

apps/log-image-classifier/Makefile
Added 'make clean' so upper level 'make clean' doesn't error out
=> added make clean

apps/image-classifier/Makefile
Added a make clean that just echoes to the terminal so upper level make clean works
=> added 'make clean' to target

apps/topcoder_example/supporting/inferences.py
Signed-off-by: Julien Lerique <klo86min@free.fr>
=> scoring modification in topcoder_example

apps/topcoder_example/supporting/inferences.py
As per https://apps.topcoder.com/forums/?module=Thread&threadID=912454&start=0, the scoring formula has been updated with a larger log_loss_max (from 7.0 to 15.0). Please do a git pull in your ncapzoo repo before making any more submissions.
=> Updated inference.py to accomodate scoring change

apps/gender_age_lbp/Makefile, apps/gender_age_lbp/cpp/gender_age_lbp.cpp
Also made resolution, text size and color changes for visibility.
=> Fixed MakeFile compile command for opencv. 

apps/gender_age_lbp/Makefile, apps/gender_age_lbp/compile.sh
Created shell script to do compile rather than doing it in the Makefile directly.  It now determines if opencv_videoio library is on the system or not and uses the correct link options accordingly.
=> modified Makefile to build for different opencv versions 

apps/image-classifier/Makefile, apps/image-classifier/README.md, apps/image-classifier/image-classifier.py, apps/live-image-classifier/Makefile, apps/live-image-classifier/README.md, apps/live-image-classifier/live-image-classifier.py, apps/rapid-image-classifier/Makefile, apps/rapid-image-classifier/README.md, apps/rapid-image-classifier/rapid-image-classifier.py
These projects will be used as a template to build other image classifier apps.
=> Classifier template

tensorflow/mnist/Makefile, tensorflow/mnist/README.md, tensorflow/mnist/run.py
Signed-off-by: Neal <neal.p.smith@intel.com>
=> Trained mnist network

apps/MultiStick_GoogLeNet/Makefile, apps/MultiStick_GoogLeNet/MultiStick_GoogLeNet.py, apps/MultiStick_GoogLeNet/python3-tk_dep_check.sh
removed compile line from MultiStick_GoogLeNet.py
removed python3-tk install line from MultiStick_GoogLeNet.py
added python3-tk dependency check and install bash script
Signed-off-by: tomevang <toemayvang86@gmail.com>
=> removed compile line and python3-tk install line from the main script

apps/MultiStick_TF_Inception/Makefile, apps/MultiStick_TF_Inception/MultiStick_Inception.py, apps/MultiStick_TF_Inception/python3-tk_dep_check.sh
removed compile line from MultiStick_GoogLeNet.py
removed python3-tk install line from MultiStick_GoogLeNet.py
added python3-tk dependency check and install bash script
Signed-off-by: tomevang <toemayvang86@gmail.com>
=> removed compile line, python3-tk install line from main program

tensorflow/inception_resnet_v2/Makefile, tensorflow/inception_resnet_v2/README.md
Signed-off-by: Michail Georgiev <mgeorgiev@mm-sol.com>
=> Adding Inception Resnet v2 example to ncappzoo

tensorflow/inception_resnet_v2/Makefile
Now will use the tf_src and tf_models project if missing env vars TF_SRC_PATH and TF_MODELS_PATH
=> Added checks for TF_SRC_PATH and TF_MODELS_PATH

tensorflow/MTCNN/AUTHORS, tensorflow/MTCNN/Makefile, tensorflow/MTCNN/README.md, tensorflow/MTCNN/run.py
Signed-off-by: Yiri <yirwen@microsoft.com>
=> add MTCNN face detection sample

apps/gender_age_lbp/cpp/gender_age_lbp.cpp
Sorting faces from left to right and using vectors for labels/colors for multiple people since the inferences aren't updated every frame.
=> fix for multiple faces 

apps/video_face_matcher_multipleFace/video_face_matcher_multiFace.py
This was based on the pull request 152, but goes a step further and just removes the unnecessary waitkey call
=> Pr 152 modified to just remove cvw.waitkey() altogether

apps/gender_age_lbp/cpp/gender_age_lbp.cpp
this matches the master branch (ncsdk1) fix done with PR169.
=> fixed the result_fp32[] array size. 

apps/mnist_calc/Makefile, apps/mnist_calc/README.md, apps/mnist_calc/calcui.py, apps/mnist_calc/mnist_processor.py, apps/mnist_calc/touchcalc.py
Signed-off-by: hmmccabe <heather.m.mccabe@intel.com>
=> mnist_calc initial commit

caffe/SSD_MobileNet/Makefile
fixed deploy prototxt file name. added merge_bn python script to generate non-batchnorm versions of the caffe and prototxt files. NCSDK2 branch.
=> Update SSD Mobilenet Makefile NCSDK2 branch

apps/topcoder_example/supporting/download_wnids.py
Signed-off-by: Jonathan Sculley <jonathanpsculley@gmail.com>
=> Add ImageNet wnid downloader helper to topcoder_example

tensorflow/ssd_mobilnet_coco/Makefile, tensorflow/ssd_mobilnet_coco/README.md, tensorflow/ssd_mobilnet_coco/coco-labels-2014_2017.txt, tensorflow/ssd_mobilnet_coco/run.py, tensorflow/ssd_mobilnet_coco/ssd_mob.config
=> added TF ssd mobilenet v1/v2 coco sample

apps/benchmark_ncs/Makefile
=> Don't run compile_model on googlenet if user provides different IR.

apps/birds/Makefile
=> removed profile and check from makefile

networks/ssd_inception_v2_food/Makefile, networks/ssd_inception_v2_food/licenses.txt, networks/ssd_inception_v2_food/ssd_inception_v2_food.py
New pull request for food model. Tying up loose ends!
=> Food ssd inception v2 more

apps/simple_classifier_py_camera/run.py
Without this commit, the `-s` / `--source` flag has no effect (other than being misleadingly output).
=> Fixed non-default camera handling in Python classifier sample

CONTRIBUTING.md
This pull request is mainly to add that a gif is recommended to include in both the networks and apps readmes.
=> Edits to contrib

caffe/AgeGenderNet/Makefile, caffe/AgeGenderNet/README.md
- Removed face-detection-retail from Makefile.
- Edited Makefile to use a default aligned image.
- Updated Readme to explain default image origin.
- Updated Readme to link to OpenVINO site.
- Added OpenVINO check to make run.
=> age gender net: Separated age gender net from face-detection-retail-0004

networks/mnist/Makefile
Signed-off-by: Neal <nealvis@gmail.com>
=> removed make model target from the make help output.

networks/emotions_recognition_retail_0003/Makefile, networks/emotions_recognition_retail_0003/README.md, networks/emotions_recognition_retail_0003/emotions_recognition_retail_0003.py
added 3 files:
1- readme for emotions_detection_retail_0004
2- Makefile for downloading emotions_detection_retail_0004 network and using face_detection makefile
3- sample code (python) for emotion detection
=> Added networks emotions recognition (networks dir)

.github/pull_request_template.md, README.md
Signed-off-by: Andrew Herrold (Intel Corporation) <andrew.herrold@intel.com>
=> added pull request template

docs/_config.yml
Signed-off-by: Andrew Herrold (Intel Corporation) <andrew.herrold@intel.com>
fixes github pages remote theme issue
=> fixed githubpages remote theme

shared/C++/Makefile, shared/Makefile, shared/Python/Makefile, shared/Python/Object_detector.py, shared/README.md
Modify this template as needed to best reflect your specific pull request.
Please state what type of addition your pull request is:    
Please include a summary of the addition or change that you are making. If making a change to an existing application or network, make sure to state which network or app you are changing. If you're making a change to an existing network or app, don't forget to update the relevant code author documentation. Failure to update ownership and authorship documentation or not including enough information for maintainers to update documentation may result in requested changes to your pull request or your pull request being closed without merging:
This PR adds the "shared" folder to the ncappzoo. This folder will contain code that is shared between different apps …
=> Adding new ncappzoo folder: shared

networks/ssd_mobilenet_v1_caffe/Ssd_mobilenet_object_detector.py
Modify this template as needed to best reflect your specific pull request.
Please state what type of addition your pull request is:    
Please include a summary of the addition or change that you are making. If making a change to an existing application or network, make sure to state which network or app you are changing. If you're making a change to an existing network or app, don't forget to update the relevant code author documentation. Failure to update ownership and authorship documentation or not including enough information for maintainers to update documentation may result in requested changes to your pull request or your pull request being closed without merging:
I am adding an Object_detector class, **Ssd_mobilenet_object_detector**, for the network ssd_mobilenet_v1_caffe. This …
=> Adding Object_detector class for ssd_mobilenet_v1_caffe

networks/tiny_yolo_v3/Tiny_yolo_v3_object_detector.py
Modify this template as needed to best reflect your specific pull request.
Please state what type of addition your pull request is:    
Please include a summary of the addition or change that you are making. If making a change to an existing application or network, make sure to state which network or app you are changing. If you're making a change to an existing network or app, don't forget to update the relevant code author documentation. Failure to update ownership and authorship documentation or not including enough information for maintainers to update documentation may result in requested changes to your pull request or your pull request being closed without merging:
I am adding an Object_detector class, Tiny_yolo_v3_object_detector, …
=> Adding Object_detector class for tiny_yolo_v3 
